(function(){
const faq = [
  { q: ["hello","hi","hey","good morning","good afternoon","good evening"], a: "Hello! Welcome to Extreme Fire Design Inc., a professional fire protection engineering company. How can we help you today?" },
  { q: ["contact","phone","call","email","address","location","where","whatsapp","reach"], a: "Phone: 0242488270/1/2/3 | Cell: +263 773 688 904 / 0719 148 295 | WhatsApp: 0776 400 176 | Email: info@extremefire.co.zw | Address: 21566 Damofalls Industrial Area, Harare, Zimbabwe | Hours: Mon-Sun 8AM-5PM" },
  { q: ["company","about","who are you","tell me about","extreme fire"], a: "Extreme Fire Design Inc. is a professional fire protection engineering company specializing in the design, supply, installation, testing, commissioning, and maintenance of fire protection systems. We provide reliable fire safety solutions designed to protect lives, property, assets, and business operations. We deliver customized solutions for commercial, industrial, residential, and high-risk environments." },
  { q: ["service","what do you do","offer","provide","solutions"], a: "Extreme Fire Design provides complete fire protection solutions:\n\n1. Fire Protection System Design - engineering design, hydraulic calculations, fire risk assessment, system layout, technical drawings, project consultation, compliance guidance\n2. Fire Sprinkler Systems - automatic sprinkler system design, supply, installation, pipework, sprinkler head installation, testing, commissioning, inspection, maintenance\n3. Fire Alarm Systems - conventional and addressable systems, smoke/heat detection, manual call points, control panels, programming, testing, maintenance\n4. Fire Pumps - electric and diesel fire pump design, installation, testing, maintenance, jockey pumps\n5. Fire Extinguishers - supply, installation, inspection, refilling, servicing (DCP, CO2, foam, water, wet chemical)\n6. Hydrant Systems & Hose Reels - design, installation, maintenance\n7. Special Suppression Systems - clean agent (FM-200, Novec, inert gases), CO2 suppression, foam systems, lithium-ion battery protection\n8. Inspection, Testing & Maintenance - preventive, corrective, and emergency maintenance" },
  { q: ["sprinkler","sprinklers","fire sprinkler"], a: "Extreme Fire Design specializes in automatic fire sprinkler systems designed to detect and control fires at an early stage. Systems include:\n\nTypes: Wet Pipe (most common, fast response), Dry Pipe (for freezing areas), Deluge (high-risk areas, large water volume), Pre-Action (data centres, museums), Foam Water (flammable liquids)\n\nComponents: Sprinkler heads (upright, pendant, sidewall, concealed), pipes and fittings (steel, galvanized, CPVC), control valves, alarm valves, water supply, fire pumps\n\nApplications: warehouses, factories, shopping centres, offices, hotels, mining facilities, industrial plants\n\nDesign Process: site assessment, hazard classification (light/ordinary/extra hazard), hydraulic calculations, installation, testing and commissioning\n\nWill all sprinklers activate? No. Each sprinkler operates individually when exposed to enough heat." },
  { q: ["alarm","detection","smoke","detect","heat detector","fire alarm"], a: "Extreme Fire Design provides fire detection and alarm solutions for early warning during fire emergencies.\n\nTypes of Control Panels:\n1. Conventional - divides building into zones, cost-effective for small buildings\n2. Addressable - every device has a unique address (e.g. 'Smoke Detector 045 in Server Room'), precise location\n3. Intelligent - advanced algorithms reduce false alarms, remote monitoring\n\nDetection Devices:\n- Smoke Detectors: photoelectric (smouldering fires), ionization (fast-flaming), aspirating/ASD (very early warning, data centres)\n- Heat Detectors: fixed temperature, rate-of-rise\n- Flame Detectors: IR, UV, UV/IR combination (fuel storage, chemical plants)\n- Gas Detection: LPG, methane, CO, hydrogen\n\nNotification: audible (sounders, bells, sirens) and visual (strobe lights, beacons)\n\nManual Call Points: break glass units near emergency exits and stairways\n\nInstallation: site survey, system design, equipment installation, programming, testing and commissioning" },
  { q: ["pump","fire pump","water supply","jockey","diesel pump","electric pump"], a: "Fire pumps provide the required water pressure and flow for fire protection systems when the available water supply cannot provide enough pressure.\n\nTypes:\n1. Electric Fire Pumps - reliable where electricity is stable, low emissions, easier maintenance\n2. Diesel Fire Pumps - operate during electrical failures, suitable for remote locations\n3. Jockey Pump - small pressure-maintaining pump that prevents unnecessary main pump starts\n4. Vertical Turbine Pumps - for large water tanks and reservoirs\n\nComponents: main fire pump, jockey pump, pump controller, fire water storage tank, valves and pipework\n\nTesting & Maintenance: weekly checks (pump condition, controller status, fuel levels), monthly checks (starting tests, battery checks, pressure checks), periodic flow and pressure testing\n\nNot all buildings need fire pumps - requirement depends on building size, fire risk, and water supply availability." },
  { q: ["extinguisher","fire extinguisher","dcp","co2","foam","wet chemical","extinguish"], a: "Extreme Fire Design supplies and services fire extinguishers for different fire risks.\n\nTypes:\n1. Dry Chemical Powder (DCP) - versatile, for Class A/B/C and electrical fires, used in offices, workshops, vehicles, industrial facilities\n2. Carbon Dioxide (CO2) - leaves no residue, safe for electronics, used in server rooms, control rooms, laboratories\n3. Foam - for Class A and flammable liquid fires, used in workshops, storage areas\n4. Water - for paper, wood, cloth (NOT for electrical or flammable liquid fires)\n5. Wet Chemical - for cooking oil and grease fires, used in commercial kitchens, restaurants\n\nPlacement: high-risk areas, emergency exits, visible and accessible with proper signage\n\nMaintenance: inspection (physical condition, pressure level, damage, labels, accessibility), servicing (internal inspection, recharging, component replacement, pressure testing)\n\nCan water extinguish electrical fires? No. Water conducts electricity and increases danger - use CO2 or DCP instead." },
  { q: ["hydrant","hose reel","hose"], a: "Fire hydrant systems provide connection points where firefighters can access water during emergencies. Hose reel systems provide a controlled water supply for first-response firefighting.\n\nHydrant Components: hydrant points (internal/external), fire hose, landing valves, hydrant pumps\n\nHose Reel Components: hose reel drum, hose pipe, nozzle, isolation valve, cabinet\n\nApplications: industrial facilities, warehouses, commercial properties, schools, shopping centres, offices\n\nBoth are commonly installed in large developments and commercial properties." },
  { q: ["clean agent","fm200","fm-200","novec","inert gas","gas suppression","special suppression"], a: "Clean agent systems use gas-based extinguishing agents to suppress fires without damaging sensitive equipment.\n\nTypes: FM-200 type agents, Novec-type agents, inert gases\n\nApplications: data centres, server rooms, telecommunications rooms, control rooms, archives\n\nAdvantages: no water damage, safe for electronics, rapid fire suppression, clean after discharge\n\nAlso available: CO2 suppression systems (for industrial equipment, generator rooms, electrical rooms) and foam suppression systems (for flammable liquid fires in fuel storage, chemical plants, aircraft hangars)." },
  { q: ["lithium","battery","thermal runaway","ev charging","battery storage"], a: "Lithium-ion batteries present unique fire challenges including thermal runaway, rapid heat release, toxic gas production, and re-ignition risk.\n\nProtection Methods:\n1. Early Detection - smoke detection, heat detection, gas detection, thermal monitoring\n2. Cooling and Suppression - water-based suppression, special suppression technologies, fire-resistant containment\n3. Continuous monitoring to identify abnormal conditions before fire develops\n\nApplications requiring protection: battery storage facilities, electric vehicle charging areas, mining equipment, renewable energy systems" },
  { q: ["data centre","server room","data center"], a: "Data centres contain sensitive electronics, high electrical loads, and critical information systems. Traditional water suppression may damage equipment.\n\nData Centre Protection Includes:\n- Very early smoke detection (aspirating/ASD)\n- Clean agent suppression (FM-200, Novec, inert gases)\n- Fire alarm systems\n- Environmental monitoring\n- Emergency shutdown systems" },
  { q: ["mining","mine","underground"], a: "Mining environments have unique fire risks from heavy machinery, fuel storage, electrical equipment, and underground operations.\n\nMining Fire Protection Solutions: fire detection systems, vehicle fire suppression, fire extinguishers, fire hydrants, water-based systems, special suppression systems" },
  { q: ["industrial","manufacturing","factory","plant"], a: "Factories often contain combustible materials, machinery, chemicals, and high-energy equipment.\n\nFire Risks: production equipment overheating, electrical faults, flammable materials, dust explosions, storage fires\n\nProtection Solutions: automatic fire sprinkler systems, fire alarm systems, fire pumps, emergency shutdown systems, fire extinguishers, fire risk assessments" },
  { q: ["warehouse","storage","picking"], a: "Warehouses can have high fire loads due to stored products and large storage areas.\n\nRisks: high-piled storage fires, packaging materials, combustible goods, forklift battery fires\n\nProtection Solutions: warehouse sprinkler systems, fire detection, fire hydrants, hose reels, smoke detection, emergency lighting integration" },
  { q: ["commercial","office","shopping","retail"], a: "Fire Protection for Commercial Buildings: fire alarm systems, emergency notification, fire extinguishers, sprinkler systems, fire safety signage, inspection programs" },
  { q: ["hospital","healthcare","clinic"], a: "Healthcare facilities require special attention because occupants may have limited mobility.\n\nProtection Solutions: addressable fire alarm systems, smoke detection, sprinkler systems, emergency communication systems, fire compartmentation support" },
  { q: ["hotel","hospitality","restaurant","kitchen","lodge"], a: "Risks: kitchen fires, guest room fires, electrical equipment, laundry equipment\n\nSolutions: fire alarm systems, kitchen suppression systems, fire extinguishers, sprinkler systems, emergency evacuation systems" },
  { q: ["power","energy","transformer","switchgear"], a: "Risks: transformers, electrical switchgear, fuel systems, high-voltage equipment\n\nSolutions: fire detection, fire suppression systems, deluge systems, fire water systems, special hazard protection" },
  { q: ["skeward","mwineya","founder","owner","technical support","30 years","nfpa certified specialist"], a: "Skeward Mwineya is the founder and Technical Support lead of Extreme Fire Design Inc.\n\nQualifications:\n- Over 30 years of experience in fire protection engineering\n- NFPA Certified Fire Protection Specialist (CFPS)\n- Member of the Society of Fire Protection Engineers (SFPE)\n- Member of the Fire Protection Association (FPA) UK\n- Member of CIBSE (UK)\n\nRole: Provides technical direction, fire protection system design, hydraulic calculations, and project oversight. He authored the company's technical publications including the Automatic Fire Sprinkler Systems Overview.\n\nSkeward's deep expertise in international fire codes (NFPA, BS EN 12845, ASIB) and decades of hands-on experience make him a leading authority on fire protection engineering in Zimbabwe and the region." },
  { q: ["skeward mwineya sprinkler","sprinkler overview","water extinguish","sprinkler pdf"], a: "Skeward Mwineya authored the Automatic Fire Sprinkler Systems Overview, a key technical publication by Extreme Fire Design Inc.\n\nKey points from his publication:\n- 'Water is an ideal extinguishing medium... has great heat absorbing capabilities'\n- Water extinguishes by: cooling fuel, impinging on fuel (reducing pyrolysis), and creating steam that displaces oxygen (smothering the fire)\n- Closed sprinklers: each has a heat-sensitive element, so only heads above the fire activate\n- The density/area method: sprinklers in a defined area all discharge at a minimum density, based on fire tests\n- Well-defined specifications help owners avoid cost overruns\n\nHis work emphasizes that properly designed sprinkler systems are the most effective and cost-efficient fire protection measure available." },
  { q: ["who is the owner","who founded","who started extreme fire","company founder"], a: "Extreme Fire Design Inc. was founded by Skeward Mwineya, a seasoned fire protection engineer with over 30 years of industry experience.\n\nHe is NFPA Certified, a member of SFPE (Society of Fire Protection Engineers), and FPA UK. His vision established Extreme Fire Design as a leading fire protection engineering firm in Zimbabwe, serving industries from power utilities to healthcare, hospitality, and high-rises.\n\nUnder his technical leadership, the company has built a reputation for engineering excellence, strict compliance with international codes (NFPA, BS EN 12845, ASIB), and reliable fire protection solutions." },
  { q: ["ncebisi","ndlovu contracts","contracts manager"], a: "Ncebisi Ndlovu is the Contracts Manager at Extreme Fire Design Inc.\n\nQualifications:\n- Degree in Fire Safety Engineering from London Metropolitan University\n\nRole: Manages project contracts, coordinates installation teams, and ensures projects are delivered on time and to specification." },
  { q: ["vusumuzi","ndhlovu health","health safety"], a: "Vusumuzi Ndhlovu is the Health & Safety Manager at Extreme Fire Design Inc.\n\nRole: Covers quality and safety standards compliance, ensuring all work meets occupational health and safety requirements and industry standards." },
  { q: ["ian mwineya","procurement"], a: "Ian Mwineya is the Procurement Manager at Extreme Fire Design Inc.\n\nBackground: Engineering and finance.\n\nRole: Manages supply chain and vendor relations for fire protection equipment and materials, ensuring quality products are sourced at competitive prices." },
  { q: ["sandrah","mhungu admin","administration manager"], a: "Sandrah Mhungu is the Administration Manager at Extreme Fire Design Inc.\n\nQualifications:\n- Bachelor of Commerce Degree in Management Accounting and Finance (University of the Witwatersrand, SA)\n- Certificates in project management\n\nRole: Manages administrative operations, financial coordination, and project management support." },
  { q: ["richard muir","alarms manager","security systems"], a: "Richard Muir is the Fire Alarms and Security Systems Manager at Extreme Fire Design Inc.\n\nQualifications:\n- Certificate in Electronics Servicing Technology Part 1 & 2 (City and Guilds, 1999-2001)\n- Installation and configuration of Impro Access Control Systems (2008)\n- Certifications in Sprinkler system acceptance\n\nRole: Manages fire alarm system design, installation, and security systems integration." },
  { q: ["value","stand for","ethics","core values"], a: "Our Core Values:\n1. Safety First - protecting people and assets through reliable fire protection solutions\n2. Quality - delivering systems and services that meet professional standards\n3. Reliability - providing dependable solutions and ongoing support\n4. Innovation - using modern technologies to improve fire safety\n5. Professionalism - maintaining high standards in engineering and customer service" },
  { q: ["vision","mission","goal"], a: "Mission: To provide innovative, reliable, and effective fire protection solutions that help organizations protect lives, assets, and operations through professional engineering, installation, and maintenance services.\n\nVision: To become a trusted leader in fire protection solutions by delivering high-quality systems, technical excellence, and exceptional customer service." },
  { q: ["client","customer","who do you work","industries served"], a: "Extreme Fire Design serves a wide range of industries including:\n- Mining operations\n- Industrial & manufacturing facilities\n- Warehouse & storage facilities\n- Commercial buildings (offices, shopping centres, retail)\n- Hospitals & healthcare facilities\n- Hospitality (hotels, lodges, restaurants)\n- Data centres & technology facilities\n- Power & energy facilities\n- Lithium battery facilities\n\nNotable clients include: Old Mutual, Mega-Pak, Delta Co-op, Joina City, ZIMSEC, Meikles Hotel, CHEP, Mutare Bottling Company, Total Zimbabwe, African Distillers, CocaCola." },
  { q: ["brand","product brand","fm200","ansul","kidde","reliable","grinnell","hygood","inbal","technoswitch","safeqip","globe","fire class"], a: "Product brands we work with: FM-200, Ansul, Reliable Sprinklers, Fire Class, Globe, Grinnell, Hygood, Inbal, Kidde, Technoswitch, SafeQIP." },
  { q: ["standard","compliance","nfpa","certification","code","regulation"], a: "Fire protection systems are designed according to recognized standards:\n\nNFPA Standards:\n- NFPA 13 - Installation of Sprinkler Systems\n- NFPA 20 - Installation of Stationary Pumps for Fire Protection\n- NFPA 25 - Inspection, Testing and Maintenance of Water-Based Systems\n- NFPA 72 - National Fire Alarm and Signaling Code\n\nOther Standards: EN 12845, ASIB Standards, BS 5839 (fire detection and alarm systems), BS EN standards, Local Authority Requirements, Building Regulations, Fire Brigade Requirements, Insurance Requirements" },
  { q: ["price","cost","quote","how much","quotation","estimate","pricing"], a: "We would be happy to provide a quotation. Please contact us directly with your project details:\n\nPhone: 0242488270/1/2/3\nEmail: info@extremefire.co.zw\n\nTo help us prepare an accurate quote, please provide:\n- Your name and company name\n- Project location\n- Building type\n- Required service (fire alarm, sprinkler, fire pump, extinguishers, maintenance, or other)\n- Project timeline" },
  { q: ["thank","thanks","appreciate","thank you"], a: "You're welcome! Feel free to reach out anytime. Stay safe! For any fire protection needs, Extreme Fire Design is here to help." },
  { q: ["design","drawing","autocad","hydraulic calculation","engineering"], a: "The fire protection design process:\n\nStep 1: Site Assessment - evaluate building structure, occupancy type, fire hazards, storage arrangements, water supply\nStep 2: Fire Risk Assessment - identify possible fire sources, fuel loads, occupant risks, critical assets\nStep 3: System Selection - choose appropriate system based on risk\nStep 4: Engineering Design - system drawings, equipment specifications, hydraulic calculations, pipe sizing, detector placement, pump selection, water demand calculations\n\nFire protection engineering involves fire risk analysis, system design, equipment selection, installation supervision, testing, maintenance, and compliance verification." },
  { q: ["maintenance","repair","service","inspect","test","inspection","itm"], a: "Regular maintenance ensures your fire protection system remains reliable.\n\nPreventive Maintenance: inspections, cleaning, adjustments, component checks\nCorrective Maintenance: repairing faults (replacing damaged detectors, repairing leaks, fixing faulty panels)\nEmergency Maintenance: urgent repairs after system failure, fire incidents, equipment damage\n\nITM Program Includes:\n- Visual Inspection: equipment condition, signs of damage, obstructions, corrosion\n- Functional Testing: device activation, alarms, pump start\n- Documentation: inspection reports, test results, maintenance history, fault records\n\nWhy maintain? A fire protection system that is not maintained may fail during an emergency." },
  { q: ["commission","install","fabricat","installation"], a: "Installation Process:\n1. Project Planning - reviewing approved designs, preparing materials, scheduling, coordinating with contractors\n2. Material Supply - pipes, sprinklers, fire alarm devices, pumps, valves, control panels, extinguishers\n3. Installation - pipe installation, sprinkler head installation, valve installation, pump connection, detector installation, cable installation, panel installation, programming\n4. System Testing - pressure testing, water flow testing, valve testing, alarm testing, detector activation, battery testing\n5. Commissioning - confirming equipment operation, system integration, documentation, client training" },
  { q: ["water mist","generator","turbine","transformer","coal","boiler"], a: "Water Mist Systems are designed for generators, power transformers, coal conveyors, switchgear, cable tunnels, turbine houses, and boiler houses." },
  { q: ["deluge","water spray"], a: "Deluge systems provide large amounts of water through open nozzles. Operation: detection system activates a deluge valve, water releases through all open nozzles. Applications: fuel storage, power plants, high-risk industrial areas." },
  { q: ["foam suppression","foam system"], a: "Foam systems are designed for fires involving flammable liquids. Foam works by separating fuel from oxygen, cooling the fire, and preventing re-ignition. Applications: fuel storage facilities, petroleum industries, chemical plants, aircraft facilities." },
  { q: ["international standard","global standard","world standard","iso standard","international code"], a: "International Fire Safety Standards:\n\nISO (International Organization for Standardization):\n- ISO 7240 - Fire detection and alarm systems (design, installation, maintenance of FDAS)\n- ISO 14520 - Gaseous fire-extinguishing systems\n- ISO 9001 - Quality management for fire protection services\n- ISO 45001 - Occupational health & safety\n- ISO 14001 - Environmental management\n\nInternational Building Code (IBC) - developed by ICC, adopted by many countries globally. Chapter 9 covers fire protection and life safety systems, including automatic sprinklers, fire alarms, standpipes, and smoke control.\n\nInternational Fire Code (IFC) - companion to IBC, covers fire prevention, fire protection systems, and life safety in existing buildings.\n\nIFSS (International Fire Safety Standards: Common Principles) - UNECE standard, 'Safe Buildings Save Lives', provides a global framework for fire safety strategies and measures." },
  { q: ["nfpa standard","nfpa code","nfpa 13","nfpa 72","nfpa 20","nfpa 25","nfpa 101","nfpa 10","nfpa 70","nfpa 96","nfpa 855"], a: "Key NFPA (National Fire Protection Association) Standards:\n\nNFPA 10 - Portable Fire Extinguishers (2026: smart monitoring now permitted for monthly visual inspections)\nNFPA 13 - Installation of Sprinkler Systems (the baseline standard)\nNFPA 13R - Low-rise residential sprinklers (up to 4 stories)\nNFPA 13D - One- and two-family dwellings\nNFPA 20 - Stationary Fire Pumps\nNFPA 25 - Inspection, Testing & Maintenance of Water-Based Systems (2026 edition: updated ITM protocols)\nNFPA 70 - National Electrical Code (2026: emergency disconnects required for EV charging stations within 50 ft)\nNFPA 72 - National Fire Alarm & Signaling Code\nNFPA 96 - Commercial Cooking Operations (2026: stricter verifiable cleaning documentation)\nNFPA 101 - Life Safety Code\nNFPA 855 - Energy Storage Systems\nNFPA 4 - Integrated System Testing\n\n2026 NFPA updates: smart monitoring for extinguishers, stricter kitchen hood documentation, EV charging safety requirements, enhanced battery energy storage rules." },
  { q: ["european standard","en 54","euro","eu","europe","germany","vde","united kingdom","uk standard","bs 5839","bs 9999"], a: "European & UK Fire Safety Standards:\n\nEN 54 Series - European standard for fire detection and alarm systems (detectors, panels, power supplies, etc.). Mandatory across EU member states.\n\nUK Standards:\n- BS 5839-1:2025 - Fire detection and alarm systems for buildings (updated with clearer system categorisation, stricter detector placement, cybersecurity requirements)\n- BS 9999 - Fire safety in the design, management, and use of buildings\n- BS 9991 - Fire safety in residential buildings\n- BS EN 13501-1 - European fire classification of construction products\n- Approved Document B - Building regulations for fire safety (England and Wales)\n\nGermany:\n- DIN 4102 / DIN EN 13501-1 - Building material classes\n- DIN VDE 0833-2 - Fire alarm systems (visual signaling device requirements)\n- Building classes (GK 1-5) define structural fire protection requirements\n\nEU Fire Safety Guide - 7 layers of fire safety: prevention, detection, warning, escape, containment, suppression, and firefighting." },
  { q: ["australian standard","australia","as 1851","as 1670","as 2444","new zealand","bca","ncc"], a: "Australian & New Zealand Fire Safety Standards:\n\nAS 1670 - Automatic fire detection and alarm systems\nAS 1841 - Portable fire extinguishers\nAS 1851 - Routine service of fire protection systems and equipment\nAS 2293 - Emergency escape lighting and exit signs\nAS 2444 - Portable fire extinguishers and fire blankets\n\nBuilding Codes of Australia / National Construction Code (BCA/NCC) - sets minimum fire safety requirements\n\nEach Australian state and territory has additional regulations. Compliance is enforced by local fire authorities." },
  { q: ["middle east","dubai","uae","saudi","gcc","civil defence"], a: "Middle East Fire Safety:\n\nGCC countries follow a mix of NFPA, British Standards, and local civil defence regulations.\n\nUAE: Dubai Civil Defence enforces strict fire safety codes. New high-rise buildings require advanced fire suppression, smoke management, and evacuation systems. Fireworks and facade fire safety have received increased attention.\n\nSaudi Arabia: Saudi Building Code (SBC) incorporates NFPA standards. High focus on fire safety in oil & gas, industrial, and commercial sectors.\n\nQatar: Qatar Civil Defence enforces Qatar Fire Code based on NFPA and British Standards.\n\nKuwait: KNPC and Kuwait Fire Service Directorate regulate industrial and commercial fire safety.\n\nThe Middle East fire protection market is growing rapidly driven by construction, oil & gas, and stringent government regulations." },
  { q: ["asia","china","japan","india","singapore","korea","hong kong","asia pacific"], a: "Asia Pacific Fire Safety:\n\nChina: GB standards (Guobiao) for fire protection. GB 50016 - Code for fire protection design of buildings. Strict enforcement after high-profile fire incidents.\n\nIndia: National Building Code (NBC) Part 4 covers fire and life safety. BIS standards for fire equipment. Growing adoption of NFPA and international standards.\n\nJapan: Building Standards Law and Fire Service Act govern fire safety. Advanced earthquake-resistant fire protection systems.\n\nSingapore: Singapore Civil Defence Force (SCDF) enforces Fire Code. Very strict enforcement in high-rise buildings, recognized globally.\n\nSouth Korea: Korea Fire Safety Institute, strict standards for high-rise and residential buildings after major fires.\n\nHong Kong: Codes of Practice for fire safety in buildings, enforced by Fire Services Department. Recent legislative changes following major fire incidents.\n\nMalaysia/Indonesia/Thailand: Mix of local standards (UBS, SNI) with increasing adoption of NFPA and international codes." },
  { q: ["africa","zimbabwe","south africa","nigeria","kenya","african standard","sabs"], a: "African Fire Safety:\n\nExtreme Fire Design Inc. is based in Zimbabwe and follows a combination of NFPA, British Standards, and local regulations.\n\nSouth Africa: SANS (South African National Standards) for fire protection. SANS 10400-T (fire protection), SANS 10139 (fire detection), SANS 1186 (fire extinguishers). OHSA (Occupational Health & Safety Act) governs workplace fire safety.\n\nNigeria: National Fire Code (NFC) and Standards Organisation of Nigeria (SON) regulate fire protection. Federal Fire Service enforcement.\n\nKenya: Kenya Bureau of Standards (KEBS) has fire safety standards. Local authorities enforce fire code compliance.\n\nAcross Africa, adoption of NFPA and British Standards is common, often modified by local regulations and building codes." },
  { q: ["global market","fire protection market","market size","industry","worldwide","global trend","cagr"], a: "Global Fire Protection Market:\n\nMarket size: ~USD 74.5 billion (2022), projected to reach USD 122-130 billion by 2030 (CAGR 6-7%).\n\nKey growth drivers:\n- Stringent fire safety regulations worldwide\n- Increasing urbanization and construction\n- Growth in lithium-ion battery and EV infrastructure requiring specialized protection\n- Adoption of smart/IoT-enabled fire detection and suppression systems\n- Retrofit projects in existing buildings\n\nRegional leaders: North America dominates, followed by Europe and Asia-Pacific.\n\nEmerging trends:\n- AI and IoT integration in fire detection\n- Smart monitoring replacing manual inspections (NFPA 10 2026)\n- Clean agent and water mist systems growth\n- Battery energy storage system (BESS) fire protection\n- Performance-based design approaches" },
  { q: ["iso certification","iso 9001","iso 45001","iso 14001","quality management","safety certification"], a: "ISO Certification for Fire Protection Companies:\n\nISO 9001:2015 - Quality Management System: ensures consistent installation, inspection, and maintenance quality\nISO 45001:2018 - Occupational Health & Safety: prevents workplace accidents during on-site work\nISO 14001:2015 - Environmental Management: controls risks from chemical agents, extinguishing media, and waste\nISO 50001:2018 - Energy Management: supports energy efficiency for manufacturing fire systems and pumps\nISO 22301:2019 - Business Continuity: keeps emergency-response operations functional during disruptions\nISO/IEC 17020 - Inspection body competence (Type A, B, or C)\n\nCertification demonstrates commitment to quality, safety, and compliance, essential for working with international clients and large-scale projects." },
  { q: ["ibc requirement","international building code chapter 9","sprinkler requirement building code","903","building code sprinkler"], a: "IBC Chapter 9 - Fire Protection & Life Safety Systems Key Requirements:\n\nAutomatic Sprinklers (IBC 903):\n- Group R (residential) and Group I (institutional): sprinklers required throughout, no size minimum\n- Group A-2 (restaurants/bars): at 5,000 sq ft or 100+ occupants\n- High-rise buildings: sprinklers required\n- Other occupancies: thresholds vary by area, story count, and fire department access\n\nStandards:\n- NFPA 13: default for all required sprinkler systems\n- NFPA 13R: Group R up to 4 stories above grade\n- NFPA 13D: one- and two-family dwellings\n\nFire Alarm Systems (IBC 907):\n- Required based on occupancy group, size, and height\n- Must be monitored by approved supervising station (NFPA 72)\n\nIntegrated Testing (NFPA 4):\n- Required for high-rise buildings and smoke control systems\n- Initial test before occupancy certificate, then every 10 years" },
  { q: ["performance based design","fire engineering","fire strategy","fire safety objective","prescriptive vs performance"], a: "Performance-Based Fire Engineering:\n\nAn alternative to prescriptive (code-minimum) design, performance-based design uses fire engineering principles to achieve fire safety objectives through scientific analysis rather than following standard code tables.\n\nApproach:\n1. Define fire safety goals (life safety, property protection, business continuity)\n2. Identify fire scenarios and design fires\n3. Analyze fire development, smoke movement, and evacuation using computer modeling (CFD, FDS, evacuation models)\n4. Evaluate structural response to fire\n5. Demonstrate that objectives are met without following prescriptive rules\n\nInternational frameworks:\n- IFSS Common Principles (UNECE)\n- NFPA 101 (Life Safety Code) allows performance-based options\n- BS 9999 provides a risk-based framework\n- IBC Chapter 1 allows alternative materials and methods\n\nUsed for: complex buildings (large atriums, tall buildings, unique architecture), where prescriptive codes are impractical or overly restrictive." },
  { q: ["global fire statistics","fire deaths","fire incidents worldwide","ctif","world fire statistics"], a: "Global Fire Statistics (CTIF World Fire Statistics Report):\n\n- Approximately 3.8 million fires reported annually across 49-80 reporting countries\n- ~26,000 civilian fire deaths per year worldwide\n- Homes without working smoke alarms account for majority of fire deaths\n- Death rate is 55-60% lower in homes with working smoke alarms\n\nEurope: ~5,000 fire deaths per year; fire fatalities reduced by 65% over the last 30 years due to comprehensive safety strategies\n\nUS: NFPA reports roughly 3 out of 5 home fire deaths occur in homes with no smoke alarms or non-working alarms\n\nFire protection systems are proven to dramatically reduce loss of life and property damage when properly designed, installed, and maintained.\n\nThe global fire protection market continues to grow as awareness and regulations become stricter worldwide." },
  { q: ["scope","what else","also do","complete","full"], a: "Our full scope:\n1. Fire Protection System Design\n2. Automatic Fire Sprinkler Systems (wet, dry, pre-action, deluge)\n3. Fire Alarm Systems (conventional, addressable, intelligent)\n4. Fire Pumps (electric, diesel, jockey, vertical turbine)\n5. Fire Extinguishers (DCP, CO2, foam, water, wet chemical)\n6. Fire Hydrant & Hose-Reel Systems\n7. Special Suppression Systems (clean agent, CO2, foam)\n8. Water Mist Systems\n9. Lithium-Ion Battery Fire Protection\n10. Fire System Inspection, Testing & Maintenance\n11. Fire Risk Assessments\n12. Compliance Support & Consultancy" },
  { q: ["why","important","need","benefit"], a: "Fire protection is important because it helps:\n- Protect human life\n- Reduce property damage\n- Minimize business interruption\n- Protect critical assets\n- Meet safety requirements\n- Improve emergency response\n\nA properly designed fire protection system provides early detection, rapid response, and effective fire control." },
  { q: ["fire class","class a","class b","class c","class d","class k","electrical fire"], a: "Fire Classifications:\n\nClass A - Ordinary combustibles (wood, paper, cloth, plastics) -> extinguish with water, foam, DCP\nClass B - Flammable liquids (petrol, diesel, oil, solvents) -> extinguish with foam, DCP, CO2\nClass C - Flammable gases (LPG, natural gas) -> extinguish with DCP\nClass D - Combustible metals (magnesium, aluminium powder) -> requires specialist agents\nElectrical Fires - caused by short circuits, overloaded circuits, equipment failure -> extinguish with CO2, DCP\nClass K/F - Cooking oil and fat fires (restaurants, commercial kitchens) -> requires wet chemical systems" },
  { q: ["fire triangle","fire develop","ignition","growth","fully developed","decay"], a: "Fire requires three elements (Fire Triangle):\n1. Heat - energy source that raises materials to ignition temperature (electrical faults, open flames, hot surfaces, friction)\n2. Fuel - any material that can burn (wood, paper, plastics, chemicals, fuel products)\n3. Oxygen - the gas that supports combustion\nRemoving one element can extinguish a fire.\n\nFire Development Stages:\n1. Ignition - fire begins when heat, oxygen, and fuel combine\n2. Growth - fire increases as more materials ignite\n3. Fully Developed - fire reaches maximum intensity\n4. Decay - fuel or oxygen reduces, causing fire to decrease" },
  { q: ["fire sprinkler reduce","sprinkler save","how effective","sprinkler death reduction","sprinkler contain"], a: "Automatic sprinklers are proven life-savers:\n\n- Sprinklers reduce civilian fire deaths by approximately 87% compared to unsprinklered properties\n- Sprinklers reduce fire injuries by approximately 27%\n- 97% of fires in sprinklered buildings are contained to their room of origin\n- Most sprinkler fires require only 1-2 head activations to control\n\nThese statistics come from NFPA data and represent one of the most cost-effective fire protection investments available." },
  { q: ["fire statistic","fire damage","fire loss","fire cost","fire billion","fire death worldwide","us fire"], a: "Fire Statistics:\n\nUS (NFPA 2024):\n- ~470,000 structure fires causing $15.3 billion in property damage\n- ~1.39 million total fire incidents with combined losses of $19.1 billion\n- 75% of structure fires occur in homes (causing ~75% of fire deaths)\n- 25% residential, 9% non-residential, 15% vehicles, 50%+ outside\n\nGlobal:\n- ~3.8 million fires annually across reporting countries\n- ~26,000 civilian fire deaths per year worldwide\n- Wildfire area burned has doubled in the past two decades\n- 2024 boreal/tropical wildfires burned ~13.5 million hectares (new record)\n\nMost destructive: 9/11 World Trade Center attack (~$57.8 billion in 2024 dollars)\nRecent major: Camp Fire 2018 California, Black Saturday 2009 Australia, Lahaina 2023 Hawaii (~102 killed)" },
  { q: ["fire cost benefit","sprinkler cost","sprinkler investment","fire protection worth","saves money"], a: "Fire protection is highly cost-effective:\n\n- A home sprinkler system typically costs approximately 1% of construction value but can avert over 90% of fire damage\n- Insurance companies often offer premium discounts of 10-50% for protected facilities\n- Workplace fires cost businesses billions annually in direct losses and months of downtime\n- NFPA data show automatic sprinklers reduce civilian fire deaths by ~87%\n- 97% of fires contained to origin room in sprinklered buildings (major savings)\n\nThe return on investment is clear: initial costs are offset by avoided losses, lower insurance claims, and continued operations." },
  { q: ["nfpa vs iso","nfpa iso difference","standards comparison","prescriptive vs risk based","nfpa en difference"], a: "Major Fire Standards Comparison:\n\nNFPA (USA/Global): Prescriptive, clear rules. Over 300 codes (NFPA 13 sprinklers, NFPA 72 alarms, NFPA 101 Life Safety). Detailed checklists, minimal guesswork. Can be rigid and voluminous.\n\nISO (International): Risk-based, management-oriented. ISO 14520 (gas suppression), ISO 7240 (detection). Flexible, adaptable, focuses on risk levels. May be abstract for designers.\n\nEN (Europe): Regulatory/testing-based. EN 12845 (sprinklers), EN 54 (detectors). Ensures product/system compliance via testing. May not cover every scenario.\n\nSANS (South Africa/Zimbabwe): SANS 10400-T (Building fire regs), SANS 1475 (Extinguishers). Largely harmonized with BS/EN.\n\nZimbabwe: No consolidated national code found. Fire safety enforced via local acts/by-laws and referenced SANS/BS/NFPA standards. EFD follows NFPA 13, BS EN 12845, and ASIB standards." },
  { q: ["fire risk sector","residential fire","cooking fire","commercial fire","industrial fire","wildfire"], a: "Fire Risks by Sector:\n\nResidential: Cooking equipment is the leading cause (~40-45% of home fires) - unattended stoves or electrical faults. Heating appliances, candles, and electrical malfunctions are also major causes.\n\nCommercial/Office: Frequently originate in electrical/technical equipment and storage areas.\n\nIndustrial: Process hazards (flammable liquids, dust explosions, high-temperature equipment).\n\nWildland: Vegetation/forest fuels and climate factors. Wildfire area burned has doubled in the past two decades.\n\nOther: Outdoor rubbish/open fires, vehicles, transformer/utility failures contribute significantly.\n\nHigh-risk occupancies: chemical plants, fuel storage, data centers, high-rises." },
  { q: ["passive fire","fire rated","compartment","fire door","fire wall"], a: "Passive Fire Protection (from EFD knowledge):\n\nPassive measures work without activation - they are built into the structure:\n- Fire-rated walls and floors create compartments to slow fire spread\n- Fire doors maintain compartmentation while allowing passage\n- Dampers in ductwork prevent fire/smoke spread through ventilation\n- Spray coatings protect structural steel\n- Flame-protected cables maintain circuit integrity\n- Compartmentation is key to occupant escape and property protection\n\nActive vs Passive: Active systems (sprinklers, alarms) detect and suppress. Passive systems contain and resist. Both are essential for comprehensive fire protection." },
  { q: ["smoke control","pressurization","smoke vent","nfpa 92"], a: "Smoke Control Systems (from EFD knowledge):\n\nSmoke is the leading killer in fires. Smoke control systems maintain tenable conditions for escape:\n\n- Pressurization fans keep stairwells and escape routes smoke-free by maintaining higher air pressure\n- Smoke ducts and vents extract smoke from the fire area\n- Smoke curtains contain smoke to specific zones\n- Mechanical exhaust systems remove smoke from large spaces\n\nStandards: NFPA 92 (Smoke Control Systems), BS EN 12101 (Smoke/ventilation)\n\nApplications: shopping centres, airports, high-rises, tunnels, large warehouses, atrium buildings" },
  { q: ["fire modeling","fds","smokeview","cfast","computer model","cfd fire"], a: "Fire Modeling & Analysis Tools:\n\nNIST FDS (Fire Dynamics Simulator): CFD tool that models fire-driven fluid flow using Navier-Stokes equations for smoke/heat. Allows visualization of smoke layers and temperature during fire scenarios.\n\nSmokeview: Visualization tool for FDS results.\n\nCFAST: Zone model for simpler fire scenarios.\n\nEvac: Egress simulation software.\n\nThese tools inform placement of detectors/vents and verify that egress paths remain tenable. Performance-based design increasingly uses computational models to validate designs in complex structures (airports, malls, high-rises)." },
  { q: ["case study fire","grenfell","kiss nightclub","fire disaster","major fire incident"], a: "Major Fire Incidents (Lessons Learned):\n\n2013 - Kiss Nightclub (Brazil): 242 killed. Acoustic foam ignited by stage flame effects. Locked exits prevented escape. Lesson: flammable interior materials and emergency egress are critical.\n\n2017 - Grenfell Tower (UK): 72 killed. Flammable exterior cladding caused rapid fire spread up the building facade. Lesson: external cladding safety and sprinkler requirements in residential towers.\n\n2023 - Lahaina Wildfire (Hawaii): ~102 killed, thousands of homes destroyed. Wildfire driven by drought and wind conditions. Lesson: wildland-urban interface planning and early warning systems.\n\n2001 - World Trade Center (USA): ~3,000 killed (terrorist attack). Costliest US fire (~$57.8 billion in 2024 dollars). Lesson: structural fire protection and evacuation in supertall buildings.\n\nEach underscores the need for rigorous design, code enforcement, and comprehensive fire protection systems." },
  { q: ["training","certification","cfps","sfpe","nicet","fire engineer qualification"], a: "Fire Protection Training & Certification:\n\nProfessional Credentials:\n- CFPS (Certified Fire Protection Specialist) - NFPA certification\n- NICET (National Council of Examiners for Engineering and Technology) - US certifications in suppression and alarms\n- SFPE (Society of Fire Protection Engineers) - professional development and courses\n\nEFD staff include NFPA-certified specialists and members of FPA UK and SFPE, indicating commitment to continuous learning.\n\nIn Zimbabwe, training may come via technical colleges or international courses.\n\nKey areas: fire extinguisher use, evacuation procedures, system awareness, regular drills, emergency response training." },
  { q: ["extinguisher class","fire class a b c d k","fire type"], a: "Fire Classifications:\n\nClass A - Ordinary combustibles (wood, paper, cloth, plastics) -> water, foam, DCP\nClass B - Flammable liquids (petrol, diesel, oil, solvents) -> foam, DCP, CO2\nClass C - Flammable gases (LPG, natural gas) -> DCP\nClass D - Combustible metals (magnesium, aluminium powder) -> specialist agents only\nElectrical Fires - caused by short circuits, overloaded circuits -> CO2, DCP (never water)\nClass K/F - Cooking oil and fat fires (commercial kitchens) -> wet chemical systems\n\nThe right extinguisher for the wrong fire class can be dangerous." },
  { q: ["prescribed burn","controlled burn","wildfire prevention","fuel load"], a: "Benefits of Controlled Fire (from EFD knowledge):\n\nWhile fire is destructive, controlled/prescribed burns have ecological benefits:\n- Reduce excess vegetation, lowering severity of later wildfires\n- Restore soil nutrients and help certain plant species regenerate\n- Manage pests and disease\n- Create fuel breaks that protect communities from catastrophic fires\n- Indigenous cultural burning practices maintain ecosystem balance\n\nPrescribed burns are a recognized land management tool used by fire services and land managers worldwide." },
  { q: ["zimbabwe fire code","zimbabwe regulation","zimbabwe law","zimbabwe standard","local code"], a: "Zimbabwe Fire Safety Regulations:\n\nZimbabwe does not have a widely published, consolidated national fire code. Fire safety is enforced through:\n- Local municipal by-laws and acts\n- Referenced international standards (SANS, BS, NFPA)\n- Building regulations referencing SANS 10400-T (Fire Protection)\n\nEFD designs per NFPA 13, BS EN 12845, and ASIB standards as referenced in their projects.\n\nFor specific Zimbabwe compliance requirements, consult with a certified fire protection engineer and local authorities." },
  { q: ["performance based","fire engineering approach","goal based","alternative design"], a: "Performance-Based Fire Design:\n\nAn alternative to prescriptive code-minimum design:\n\n1. Define fire safety goals (life safety, property protection, business continuity)\n2. Identify fire scenarios and design fires\n3. Analyze fire development, smoke movement, and evacuation using computer modeling (FDS, CFAST, evacuation models)\n4. Evaluate structural response to fire\n5. Demonstrate objectives are met without following prescriptive rules\n\nEFD describes this as: 'established fire safety goals and objectives, analysis of fire scenarios, and quantitative assessment of design alternatives'\n\nUsed for complex buildings (large atriums, tall buildings, unique architecture) where prescriptive codes are impractical." },
  { q: ["fm200 how works","clean agent mechanism","fm200 chemistry","gas suppression mechanism"], a: "FM-200 (HFC-227ea) Clean Agent System:\n\nHow it works: FM-200 extinguishes by interrupting the fire chemistry (chain reaction of combustion), NOT by oxygen depletion or asphyxiation.\n\nKey specs:\n- Discharged within 10 seconds\n- Typical design concentration: 7.9-8.5% per ISO 14520\n- Safe for occupied spaces at design concentration\n- No ozone depletion\n- Minimal residue - safe for electronics\n- Compact cylinder storage\n\nStandards: NFPA 2001 (Clean Agent), ISO 14520, EN 15004\n\nApplications: data centres, server rooms, telecom rooms, control rooms, archives, museums" },
  { q: ["sprinkler type","wet dry deluge preaction","sprinkler system type"], a: "Sprinkler System Types (from EFD documentation):\n\nWet Pipe: Most common, fast response. Pipes always filled with pressurized water. Ideal for occupied buildings above freezing.\n\nDry Pipe: Air-pressurized pipes. Used in freezing areas (warehouses, parking garages). Water enters when air is released.\n\nPre-Action: Electrically controlled valve. Water enters only when both detection system AND sprinkler activate. Used in data centres, museums.\n\nDeluge: Open pipes with open nozzles. Flood entire area. Used for high-risk areas (fuel storage, aircraft hangars).\n\nEach type has specific applications based on hazard level, temperature, and occupancy." },
];

function findAnswer(msg) {
  const m = msg.toLowerCase().replace(/[^a-z0-9\s]/g, '');
  for (const item of faq) {
    for (const keyword of item.q) {
      if (m.includes(keyword)) return item.a;
    }
  }
  return null;
}

function getReply(msg) {
  const direct = findAnswer(msg);
  if (direct) return direct;
  const m = msg.toLowerCase();
  if (/\b(yes|yeah|sure|okay|ok)\b/.test(m)) return "Great! Let us know what you need help with regarding fire protection.";
  return "Thank you for reaching out to Extreme Fire Design Inc. For specific information about your project, please contact us directly at info@extremefire.co.zw or call 0242488270/1/2/3. One of our engineers would be happy to assist you with a professional assessment and tailored solution.";
}

const chatStyle = document.createElement('style');
chatStyle.textContent = `
#chat-close{width:100%;padding:10px;border-radius:0 0 16px 16px;background:rgba(255,255,255,0.06);color:rgba(255,255,255,0.5);font-size:1rem;display:flex;align-items:center;justify-content:center;cursor:pointer;transition:all 0.2s;border-top:1px solid rgba(255,255,255,0.08)}
#chat-close:hover{background:rgba(255,255,255,0.1);color:#fff}
#chat-header span{flex:1}
`;
document.head.appendChild(chatStyle);

const chatHTML = `
<div id="chat-widget">
  <button id="chat-toggle" aria-label="Open chat"><svg viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2"><path d="M21 15a2 2 0 0 1-2 2H7l-4 4V5a2 2 0 0 1 2-2h14a2 2 0 0 1 2 2z"/></svg></button>
  <div id="chat-panel">
    <div id="chat-header"><span>Extreme Fire Design Assistant</span></div>
    <div id="chat-messages"><div class="chat-msg bot">Hi! Welcome to Extreme Fire Design Inc. How can I help you with fire protection today?</div></div>
    <form id="chat-form"><input id="chat-input" placeholder="Type your message..." autocomplete="off"><button type="submit">Send</button></form>
    <div id="chat-close">&times; Close chat</div>
  </div>
</div>`;
document.body.insertAdjacentHTML('beforeend', chatHTML);

const toggle = document.getElementById('chat-toggle');
const panel = document.getElementById('chat-panel');
const close = document.getElementById('chat-close');
const form = document.getElementById('chat-form');
const input = document.getElementById('chat-input');
const messages = document.getElementById('chat-messages');

// Move panel out of #chat-widget so position:fixed escapes the parent stacking context
document.body.appendChild(panel);

// Inject CSS rules for positioning (desktop + mobile fullscreen)
const panelCSS = document.createElement('style');
panelCSS.textContent = '#chat-panel{position:fixed;bottom:164px;right:24px}@media(max-width:768px){#chat-panel,#chat-panel.open{position:fixed!important;top:0!important;left:0!important;right:0!important;bottom:0!important;width:100vw!important;height:100dvh!important;max-height:none!important;border-radius:0!important;border:none!important;z-index:10002!important}#chat-panel.open{display:flex!important;flex-direction:column!important;overflow:hidden!important;background:#0b1220!important}}';
document.head.appendChild(panelCSS);

function isMobile(){return window.innerWidth<=768}
var mobileProps=[['position','fixed'],['top','0'],['left','0'],['right','0'],['bottom','0'],['width','100vw'],['height','100dvh'],['max-height','none'],['border-radius','0'],['border','none'],['z-index','10002'],['display','flex'],['flex-direction','column'],['overflow','hidden'],['background','#0b1220']];
function applyMobileStyles(){if(!isMobile())return;mobileProps.forEach(function(p){panel.style.setProperty(p[0],p[1],'important')})}
function clearMobileStyles(){mobileProps.forEach(function(p){panel.style.removeProperty(p[0])})}

toggle.onclick=function(){panel.classList.toggle('open');panel.classList.contains('open')?applyMobileStyles():clearMobileStyles()};
close.onclick=function(){panel.classList.remove('open');clearMobileStyles()};

var heroBtn=document.getElementById('hero-chat-btn');
if(heroBtn){heroBtn.addEventListener('click',function(){panel.classList.add('open');applyMobileStyles()})}

window.addEventListener('resize',function(){if(panel.classList.contains('open')){isMobile()?applyMobileStyles():clearMobileStyles()}});

form.onsubmit = (e) => {
  e.preventDefault();
  const text = input.value.trim();
  if (!text) return;
  input.value = '';
  const safe = text.replace(/&/g,'&amp;').replace(/</g,'&lt;').replace(/>/g,'&gt;').replace(/"/g,'&quot;');
  messages.innerHTML += `<div class="chat-msg user">${safe}</div>`;
  const reply = getReply(text);
  setTimeout(() => {
    messages.innerHTML += `<div class="chat-msg bot">${reply}</div>`;
    messages.scrollTop = messages.scrollHeight;
  }, 300);
  messages.scrollTop = messages.scrollHeight;
};
})();
